spring.application.name=afric-hello-world
server.port=8080

app.environment=${APP_ENV:production}
app.version=1.0.0

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Info endpoint
info.app.name=@fric Hello World
info.app.version=1.0.0
info.app.description=Lead DevOps Technical Test
